# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Install dependencies
    - name: Install dependent libraries
      run: |
        sudo apt-get install libgsl0-dev
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Setup Julia environment
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U numpy scipy
        cd $GITHUB_WORKSPACE
        git clone https://gitlab.com/qmml/qmmlpack.git
        cd qmmlpack
        ./make -v cpp --include-path="/usr/include/gsl"
        ./make -v python --include-path="/usr/include/gsl"
        ./make -v install
        cd $GITHUB_WORKSPACE/MBTR.jl
        export PYTHONPATH="/usr/local/qmmlpack/python:$PYTHONPATH"
    - name: Setup Julia environment
      uses: julia-actions/setup-julia@latest
      with:
        # The Julia version to download (if necessary) and use.
        version: 1.3
        # Display InteractiveUtils.versioninfo() after installing
        show-versioninfo: true # optional, default is false
    - run: |
        using InteractiveUtils; versioninfo()
        using Pkg; Pkg.activate("."); Pkg.test("MBTR")
      shell: bash -c "julia --color=yes --project {0}"
